import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import axios from "axios";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

const getData = async () => {
  const cookieStore = cookies();
  const sessionCookie = cookieStore.get("session")?.value;
  console.log("cokiee__", sessionCookie);
  console.log("cokieestore__", cookieStore);

  if (!sessionCookie) {
    console.error("Session cookie is undefined");
    return null;
  }

  try {
    const { data } = await axios.get(
      "http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/api/users/currentuser",
      {
        headers: {
          Host: "ticketing.dev",
          Cookie: `session=${sessionCookie}`, // Pass the session cookie in the Cookie header
        },
      }
    );
    console.log("first__", data);
    return data;
  } catch (error) {
    console.error("Error fetching data:", error);
    return null;
  }
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await getData();
  console.log("second__", data);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header currentUser={data?.currentUser} />
        {children}
      </body>
    </html>
  );
}
